export const INCREMENT =  'INCREMENT';
export const DECREMENT =  'DECREMENT';

export const SIGN_IN_REQUEST = '@auth/SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = '@auth/SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = '@auth/SIGN_IN_FAILURE';
export const SIGN_OUT_REQUEST = '@auth/SIGN_OUT_REQUEST';

export const REGISTER_REQUESTER = 'REGISTER_REQUESTER';

export const REGISTER_PRODUCT_REQUEST = 'REGISTER_PRODUCT_REQUEST';
export const REGISTER_PRODUCT_SUCESS = 'REGISTER_PRODUCT_SUCESS';
export const REGISTER_PRODUCT_UPDATE = 'REGISTER_PRODUCT_UPDATE';
export const REGISTER_PRODUCT_DELETE = 'REGISTER_PRODUCT_DELETE';
export const REGISTER_PRODUCT_FAILURE = 'REGISTER_PRODUCT_FAILURE';